In [ ]:
import h5py
import scipy.io
import matplotlib.pyplot as plt
import numpy as np
import pickle

In [ ]:
matFilename = './datasets/2018-08-28_batchdata_updated_struct_errorcorrect.mat'
f = h5py.File(matFilename)

In [ ]:
matFilename = './datasets/2018-04-12_batchdata_updated_struct_errorcorrect-001.mat'
f = h5py.File(matFilename)

In [ ]:
matFilename = './datasets/2018-04-03_varcharge_batchdata_updated_struct_errorcorrect.mat'
f = h5py.File(matFilename)

In [ ]:
list(f.keys())

In [ ]:
batch = f['batch']

In [ ]:
list(batch.keys())

In [80]:
num_cells = batch['summary'].shape[0] #find size (number of summary data)
bat_dict = {}
for i in range(num_cells):
    cl = f[batch['cycle_life'][i,0]][::2]
    # policy = f[batch['policy_readable'][i,0]].value.tobytes()[::2].decode() <-- deprecated, need some other way to dissect code
    policy = f[batch['policy_readable'][i,0]]
    summary_IR = np.hstack(f[batch['summary'][i,0]]['IR'][0,:].tolist())
    summary_QC = np.hstack(f[batch['summary'][i,0]]['QCharge'][0,:].tolist())
    summary_QD = np.hstack(f[batch['summary'][i,0]]['QDischarge'][0,:].tolist())
    summary_TA = np.hstack(f[batch['summary'][i,0]]['Tavg'][0,:].tolist())
    summary_TM = np.hstack(f[batch['summary'][i,0]]['Tmin'][0,:].tolist())
    summary_TX = np.hstack(f[batch['summary'][i,0]]['Tmax'][0,:].tolist())
    summary_CT = np.hstack(f[batch['summary'][i,0]]['chargetime'][0,:].tolist())
    summary_CY = np.hstack(f[batch['summary'][i,0]]['cycle'][0,:].tolist())
    summary = {'IR': summary_IR, 'QC': summary_QC, 'QD': summary_QD, 'Tavg':
                summary_TA, 'Tmin': summary_TM, 'Tmax': summary_TX, 'chargetime': summary_CT,
                'cycle': summary_CY}
                
    cycles = f[batch['cycles'][i,0]]
    cycle_dict = {}
    for j in range(cycles['I'].shape[0]):
        I = np.hstack((f[cycles['I'][j,0]]))
        Qc = np.hstack((f[cycles['Qc'][j,0]]))
        Qd = np.hstack((f[cycles['Qd'][j,0]]))
        Qdlin = np.hstack((f[cycles['Qdlin'][j,0]]))
        T = np.hstack((f[cycles['T'][j,0]]))
        Tdlin = np.hstack((f[cycles['Tdlin'][j,0]]))
        V = np.hstack((f[cycles['V'][j,0]]))
        dQdV = np.hstack((f[cycles['discharge_dQdV'][j,0]]))
        t = np.hstack((f[cycles['t'][j,0]]))
        cd = {'I': I, 'Qc': Qc, 'Qd': Qd, 'Qdlin': Qdlin, 'T': T, 'Tdlin': Tdlin, 'V':V, 'dQdV': dQdV, 't':t}
        cycle_dict[str(j)] = cd
        
    cell_dict = {'cycle_life': cl, 'charge_policy':policy, 'summary': summary, 'cycles': cycle_dict}
    key = 'b1c' + str(i)
    bat_dict[key]=   cell_dict

In [91]:
strlist = ""
for c in bat_dict['b1c0']['charge_policy']:
    strlist = strlist + chr(c[0])
print(strlist)

4-6-5.6-4.2


In [77]:
bat_dict.keys()

dict_keys(['b1c0', 'b1c1', 'b1c2', 'b1c3', 'b1c4', 'b1c5', 'b1c6', 'b1c7', 'b1c8', 'b1c9', 'b1c10', 'b1c11', 'b1c12', 'b1c13', 'b1c14', 'b1c15', 'b1c16', 'b1c17', 'b1c18', 'b1c19', 'b1c20', 'b1c21', 'b1c22', 'b1c23', 'b1c24', 'b1c25', 'b1c26', 'b1c27', 'b1c28', 'b1c29', 'b1c30', 'b1c31', 'b1c32', 'b1c33', 'b1c34', 'b1c35', 'b1c36', 'b1c37', 'b1c38', 'b1c39', 'b1c40', 'b1c41', 'b1c42', 'b1c43', 'b1c44', 'b1c45'])

In [82]:
bat_dict['b1c0']['cycle_life']

array([[nan]])

In [109]:
#To be fixed (why is the shape 11 when there are 46 entries??)
bat_dict['b1c0']['charge_policy'][:][0]


array([52], dtype=uint16)

In [42]:
bat_dict['b1c43']['summary']

{'IR': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]),
 'QC': array([1.0719081, 1.0733508, 1.0744466, 1.075135 , 1.0758506, 1.0761497,
        1.0765046, 1.0768093, 1.0771062, 1.0771534, 1.0773457, 1.0771605,
        1.0775129, 1.0773184, 1.0774654, 1.0775222, 1.0778667, 1.077778 ,
        1.0779037, 1.0779259, 1.0778773, 1.0779941, 1.0779485, 1.078097 ,
        1.0780438, 1.078028 , 1.0782999, 1.0782535, 1.0781233, 1.0780267,
        1.0780995, 1.0780213, 1.0777533, 1.0777843, 1.0778869, 1.0777988

In [ ]:
#Access Summary data

In [36]:
bat_dict['b1c43']['summary']['QC']

array([1.0719081, 1.0733508, 1.0744466, 1.075135 , 1.0758506, 1.0761497,
       1.0765046, 1.0768093, 1.0771062, 1.0771534, 1.0773457, 1.0771605,
       1.0775129, 1.0773184, 1.0774654, 1.0775222, 1.0778667, 1.077778 ,
       1.0779037, 1.0779259, 1.0778773, 1.0779941, 1.0779485, 1.078097 ,
       1.0780438, 1.078028 , 1.0782999, 1.0782535, 1.0781233, 1.0780267,
       1.0780995, 1.0780213, 1.0777533, 1.0777843, 1.0778869, 1.0777988,
       1.0776162, 1.0776097, 1.0776318, 1.0779371, 1.0779591, 1.0778869,
       1.0777824, 1.0779618, 1.077844 , 1.0778989, 1.0778772, 1.0775394,
       1.077813 , 1.0778415, 1.077906 , 1.0777991, 1.0775919, 1.0775777,
       1.0775063, 1.0777125, 1.0775907, 1.0776671, 1.0774248, 1.0775915,
       1.0776097, 1.0775036, 1.0775247, 1.0774704, 1.0773977, 1.0776716,
       1.0773654, 1.0775716, 1.0775669, 1.077262 , 1.0772336, 1.0770835,
       1.0771991, 1.0771121, 1.0771651, 1.0772041, 1.0771546, 1.0771365,
       1.0770781, 1.0767019, 1.076882 , 1.0766737, 

In [37]:
#Access invidual cell
bat_dict['b1c43']['summary']['QC'][i]

1.0719081

In [ ]:
#Access Cycle Data

In [55]:
bat_dict['b1c43']['cycles']['2']

{'I': array([0.33409119, 0.52251643, 0.71358074, ..., 0.        , 0.        ,
        0.        ]),
 'Qc': array([2.0369478e-06, 2.0369478e-06, 2.0369478e-06, ..., 1.0744466e+00,
        1.0744466e+00, 1.0744466e+00]),
 'Qd': array([4.6778979e-07, 4.6778979e-07, 4.6778979e-07, ..., 1.0749913e+00,
        1.0749913e+00, 1.0749913e+00]),
 'Qdlin': array([-1.30748309e-04, -9.71577832e-05, -6.32889413e-05, -2.92391579e-05,
         4.89419254e-06,  3.90137358e-05,  7.30220974e-05,  1.06821903e-04,
         1.40315779e-04,  1.73406349e-04,  2.05996241e-04,  2.37988079e-04,
         2.69327351e-04,  3.00203956e-04,  3.30894301e-04,  3.61674891e-04,
         3.92822232e-04,  4.24612832e-04,  4.57323197e-04,  4.91197624e-04,
         5.26265339e-04,  5.62467477e-04,  5.99744906e-04,  6.38038496e-04,
         6.77289114e-04,  7.17437631e-04,  7.58428634e-04,  8.00256129e-04,
         8.42949208e-04,  8.86537707e-04,  9.31051466e-04,  9.76520322e-04,
         1.02297411e-03,  1.07043126e-03,  1.

In [41]:
#Size of data
bat_dict['b1c43']['cycles']['2']['I'].shape[0]

1380

In [35]:
#Access invidual cell
bat_dict['b1c43']['cycles']['2']['I'][i]

4.799964181818181

In [ ]:
#Rubbish Matplotlib stuff

In [ ]:
#batchdata
plt.plot(bat_dict['b1c43']['summary']['cycle'], bat_dict['b1c43']['summary']['QD'])

In [ ]:
plt.plot(bat_dict['b1c43']['cycles']['10']['Qd'], bat_dict['b1c43']['cycles']['10']['V'])

In [ ]:
#varcharge
plt.plot(bat_dict['b3c0']['summary']['cycle'], bat_dict['b3c0']['summary']['QD'])